# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#
# You must run next command first time:
#     pre-commit install
#
default_stages: [commit]
repos:
  -   repo: https://github.com/ambv/black
      rev: 21.7b0
      hooks:
      -   id: black
          args: [--line-length=79, --skip-string-normalization]
  -   repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2
      hooks:
      -   id: flake8
          args: [--config=.flake8]
          exclude: |
            (
            ^coverage_html_report/|
            ^log/|
            ^migrations/|
            ^node_modules/|
            ^venv/
            )
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
      -   id: trailing-whitespace
      -   id: double-quote-string-fixer
  -   repo: https://github.com/asottile/reorder_python_imports
      rev: v2.6.0
      hooks:
      -   id: reorder-python-imports
  -   repo: https://github.com/asottile/pyupgrade
      rev: v2.23.3
      hooks:
      -   id: pyupgrade
  -   repo: https://github.com/commitizen-tools/commitizen
      rev: v2.17.13
      hooks:
      -   id: commitizen
          stages: [commit-msg]