"""Add tbl_book_stocks unique constraint with country_id and book_id

Revision ID: 136511e872b2
Revises: 9b92b7f9419b
Create Date: 2021-06-03 20:41:30.947460

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '136511e872b2'
down_revision = '9b92b7f9419b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        'uq_tbl_book_stocks_book_id_country_id',
        'tbl_book_stocks',
        ['country_id', 'book_id'],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'uq_tbl_book_stocks_book_id_country_id',
        'tbl_book_stocks',
        type_='unique',
    )
    # ### end Alembic commands ###
