"""Add unique constraint book price to book and country columns

Revision ID: 6237364477c5
Revises: ac118cd2cdda
Create Date: 2021-05-17 22:29:38.759467

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '6237364477c5'
down_revision = 'ac118cd2cdda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        'uq_tbl_book_prices_country_id_book_id',
        'tbl_book_prices',
        ['country_id', 'book_id'],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'uq_tbl_book_prices_country_id_book_id',
        'tbl_book_prices',
        type_='unique',
    )
    # ### end Alembic commands ###
