"""Delete country_id from tbl_countries table

Revision ID: 7889d813b948
Revises: fdb7f933a7e2
Create Date: 2021-05-03 18:15:30.706778

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7889d813b948'
down_revision = 'fdb7f933a7e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_tbl_countries_tbl_currencies', 'tbl_countries', type_='foreignkey'
    )
    op.drop_column('tbl_countries', 'country_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'tbl_countries',
        sa.Column(
            'country_id', mysql.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        'fk_tbl_countries_tbl_currencies',
        'tbl_countries',
        'tbl_currencies',
        ['country_id'],
        ['id'],
    )
    # ### end Alembic commands ###
