"""Add new units column to tbl_shopping_cart_books table

Revision ID: 88b3efa25cd9
Revises: ba290bcd39d5
Create Date: 2021-11-19 18:42:15.996356

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '88b3efa25cd9'
down_revision = 'ba290bcd39d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'tbl_shopping_cart_books',
        sa.Column('units', sa.Integer(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_shopping_cart_books', 'units')
    # ### end Alembic commands ###
