"""Add new total_price to tbl_shopping_carts table and remove vat from tbl_book_prices table  # noqa

Revision ID: 95a877c8d06b
Revises: 99f3642f085f
Create Date: 2021-11-30 19:19:17.467219

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '95a877c8d06b'
down_revision = '99f3642f085f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_book_prices', 'vat')
    op.add_column(
        'tbl_shopping_carts',
        sa.Column('total_price', sa.Float(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_shopping_carts', 'total_price')
    op.add_column(
        'tbl_book_prices', sa.Column('vat', mysql.FLOAT(), nullable=False)
    )
    # ### end Alembic commands ###
