"""Remove discount column from tbl_shopping_cart_books table

Revision ID: 99f3642f085f
Revises: 88b3efa25cd9
Create Date: 2021-11-30 18:43:02.591420

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99f3642f085f'
down_revision = '88b3efa25cd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_shopping_cart_books', 'discount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'tbl_shopping_cart_books',
        sa.Column(
            'discount', mysql.DECIMAL(precision=10, scale=2), nullable=False
        ),
    )
    # ### end Alembic commands ###
