"""Update tbl_shopping_cart_books discount column

Revision ID: b54058e21e09
Revises: 136511e872b2
Create Date: 2021-07-19 21:08:01.104759

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b54058e21e09'
down_revision = '136511e872b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'tbl_shopping_cart_books',
        'discount',
        existing_type=mysql.FLOAT(),
        type_=sa.Numeric(precision=10, scale=2, asdecimal=False),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'tbl_shopping_cart_books',
        'discount',
        existing_type=sa.Numeric(precision=10, scale=2, asdecimal=False),
        type_=mysql.FLOAT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
