"""Rename quantity column from tbl_book_stocks table to stock

Revision ID: ba290bcd39d5
Revises: d7d4c9e6d6b7
Create Date: 2021-11-19 18:30:19.924844

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba290bcd39d5'
down_revision = 'd7d4c9e6d6b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'tbl_book_stocks', sa.Column('stock', sa.Integer(), nullable=False)
    )
    op.drop_column('tbl_book_stocks', 'quantity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'tbl_book_stocks',
        sa.Column(
            'quantity',
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column('tbl_book_stocks', 'stock')
    # ### end Alembic commands ###
