"""Remove numeric_code column from tbl_countries

Revision ID: ccff1682143e
Revises: ce0062fbc4ae
Create Date: 2021-05-04 19:41:09.720974

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ccff1682143e'
down_revision = 'ce0062fbc4ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_countries', 'numeric_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'tbl_countries',
        sa.Column(
            'numeric_code',
            mysql.VARCHAR(collation='utf8_bin', length=3),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
