"""Add currency_id column to tbl_countries

Revision ID: ce0062fbc4ae
Revises: 7889d813b948
Create Date: 2021-05-03 18:16:44.691148

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'ce0062fbc4ae'
down_revision = '7889d813b948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'tbl_countries', sa.Column('currency_id', sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        'fk_tbl_countries_tbl_currencies',
        'tbl_countries',
        'tbl_currencies',
        ['currency_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_tbl_countries_tbl_currencies', 'tbl_countries', type_='foreignkey'
    )
    op.drop_column('tbl_countries', 'currency_id')
    # ### end Alembic commands ###
