"""Update unique constraint from tbl_countries

Revision ID: dafdfd716cc2
Revises: d7cfc86c6e35
Create Date: 2021-05-06 18:53:27.043039

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'dafdfd716cc2'
down_revision = 'd7cfc86c6e35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        'uq_tbl_countries_name_alpha_2_code_alpha_3_code',
        'tbl_countries',
        ['name', 'alpha_2_code', 'alpha_3_code'],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'uq_tbl_countries_name_alpha_2_code_alpha_3_code',
        'tbl_countries',
        type_='unique',
    )
    # ### end Alembic commands ###
