"""New currency columns

Revision ID: fdb7f933a7e2
Revises: 70f517aedf18
Create Date: 2021-04-29 20:14:21.385121

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'fdb7f933a7e2'
down_revision = '70f517aedf18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'tbl_currencies',
        sa.Column('name_plural', sa.String(length=255), nullable=False),
    )
    op.add_column(
        'tbl_currencies',
        sa.Column('symbol', sa.String(length=10), nullable=False),
    )
    op.add_column(
        'tbl_currencies',
        sa.Column('symbol_native', sa.String(length=10), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_currencies', 'symbol_native')
    op.drop_column('tbl_currencies', 'symbol')
    op.drop_column('tbl_currencies', 'name_plural')
    # ### end Alembic commands ###
